###
POST http://localhost:4132/api/create/note
#POST http://localhost:4132/create/itemType
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk5Y2VkMTljLWJlMjMtNDBjZS05MDQyLTRhYzE2YTdiMDEyMCIsIm5hbWUiOiJqdWFuIiwiaWF0IjoxNzY1OTAyOTA2LCJleHAiOjE3NjYyNjI5MDZ9.5PsqSsxIG-aF0zBORGMj-D4wlmp7knC2yQNqrvzdB8o

{
  "name": "this is a new note",
  "description": "new"
}


### 
PUT http://localhost:4132/api/update/task/4 
# PUT http://localhost:4132/update/itemTable/itemId
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk5Y2VkMTljLWJlMjMtNDBjZS05MDQyLTRhYzE2YTdiMDEyMCIsIm5hbWUiOiJqdWFuIiwiaWF0IjoxNzY1OTAyOTA2LCJleHAiOjE3NjYyNjI5MDZ9.5PsqSsxIG-aF0zBORGMj-D4wlmp7knC2yQNqrvzdB8o

{
  "visibility": "public"
}

#task -> name, desc, status
#note -> name, desc
#folder -> name, parent_id


### 
DELETE http://localhost:4132/api/delete/task/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNkNjNjMjM4LWIxMTctNDY0MC1hYTVlLTFiNWFjYjVkYzkwNSIsIm5hbWUiOiJqdWFuIiwiaWF0IjoxNzYzNjczOTk3LCJleHAiOjE3NjQwMzM5OTd9.NDOOB_JzUcIh4GWi4yAgDDCKTd07WYvg116UQeMNK3o

###
PUT http://localhost:4132/api/add/favorite/task/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk5Y2VkMTljLWJlMjMtNDBjZS05MDQyLTRhYzE2YTdiMDEyMCIsIm5hbWUiOiJqdWFuIiwiaWF0IjoxNzYzNzMxNTIzLCJleHAiOjE3NjQwOTE1MjN9.Vor_CR0Hfp06fQLT7vDxQidivoFOxKNg7pzl8RK2NfY


###
POST http://localhost:4132/api/add/to-folder/task/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk5Y2VkMTljLWJlMjMtNDBjZS05MDQyLTRhYzE2YTdiMDEyMCIsIm5hbWUiOiJqdWFuIiwiaWF0IjoxNzYzNzMxNTIzLCJleHAiOjE3NjQwOTE1MjN9.Vor_CR0Hfp06fQLT7vDxQidivoFOxKNg7pzl8RK2NfY

{
  "itemIds": [4]
}

###
POST http://localhost:4132/api/add/ea3ce064-dff6-4016-a1d0-005bee72a131/note/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk5Y2VkMTljLWJlMjMtNDBjZS05MDQyLTRhYzE2YTdiMDEyMCIsIm5hbWUiOiJqdWFuIiwiaWF0IjoxNzY1OTAyOTA2LCJleHAiOjE3NjYyNjI5MDZ9.5PsqSsxIG-aF0zBORGMj-D4wlmp7knC2yQNqrvzdB8o

{
  "role": "viewer" 
}
###
POST http://localhost:4132/api/update/ea3ce064-dff6-4016-a1d0-005bee72a131/note/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk5Y2VkMTljLWJlMjMtNDBjZS05MDQyLTRhYzE2YTdiMDEyMCIsIm5hbWUiOiJqdWFuIiwiaWF0IjoxNzY1OTAyOTA2LCJleHAiOjE3NjYyNjI5MDZ9.5PsqSsxIG-aF0zBORGMj-D4wlmp7knC2yQNqrvzdB8o

{
  "role": "viewer" 
}