POST http://localhost:4132/signup
Content-Type: application/json

{
  "name": "juan",
  "email": "juan@gmail.com",
  "password": "juan.dev"
}
###
POST http://localhost:4132/signin
Content-Type: application/json

{
  "name": "juan",
  "email": "juan@gmail.com",
  "password": "juan.dev"  
}
### 
GET http://localhost:4132/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk5Y2VkMTljLWJlMjMtNDBjZS05MDQyLTRhYzE2YTdiMDEyMCIsIm5hbWUiOiJqdWFuIiwiaWF0IjoxNzYzNzMxNTIzLCJleHAiOjE3NjQwOTE1MjN9.Vor_CR0Hfp06fQLT7vDxQidivoFOxKNg7pzl8RK2NfY

